apiVersion: v1 
kind: Secret
metadata:
  name: app-secret
  labels:
    app: FINTRACK

type: Opaque
data:
  DB_USER: cG9zdGdyZXM=           #BASE64
  DB_PASSWORD: R3VpengyMDAz       #BASE64
  DB_NAME: cHJvamV0b2luZA==       #BASE64
